services:
  pgsql:
    image: postgres:18.0-alpine3.22
    container_name: sympa-pgsql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sympa -d sympa || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20


  mailhog:
    image: mailhog/mailhog
    container_name: sympa-mailhog
    ports:
      - "8025:8025"
  sympa:
    build:
      context: .
      dockerfile: latest.dockerfile   # on utilise SON Dockerfile, en local
    container_name: sympa-app
    depends_on:
      pgsql:
        condition: service_healthy
    ports:
      - "8023:80"
    volumes:
      # config sympa
      - ./sympa.conf:/etc/sympa/sympa/sympa.conf
      # volumes de données
      - ./nullmailer/remotes:/etc/nullmailer/remotes:ro
      - sympa_spool:/var/spool/sympa
      - sympa_data:/var/lib/sympa
      - sympa_shared:/etc/sympa/shared


volumes:
  pg_data:
  sympa_spool:
  sympa_data:
  sympa_shared:
