## Global Sympa config

domain       localhost
listmaster   postmaster@tondomaine.tld

wwsympa_url  http://localhost:8080/sympa

db_type      PostgreSQL
db_host      pgsql
db_port      5432
db_name      sympa
db_user      sympa
db_passwd    sympa

